name = "208848"
main = "cloudflare/worker.ts"
compatibility_date = "2026-05-22"
pages_build_output_dir = "out"
routes = [
  { pattern = "208848.xyz/api/rooms", zone_name = "208848.xyz" },
  { pattern = "208848.xyz/api/rooms/*", zone_name = "208848.xyz" },
]

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDurableObject"]
