import { config } from "./shared.ts";

export function aimConfigs() {
  return [
    config(1, "aim-track", "过关要求：8 箭全中圆形轨迹靶。", {
      aimMode: "track",
      arrowCount: 8,
      targetCount: 8,
      route: "circle",
      failOnFlyOut: false,
      decoyCount: 0,
      targetSize: 58,
      targetSpeed: 0.0016,
    }),
    config(2, "aim-incoming", "过关要求：连续命中所有飞入靶，靶子飞出算失败。", {
      aimMode: "incoming",
      arrowCount: 8,
      targetCount: 8,
      route: "incoming",
      failOnFlyOut: true,
      spawnIntervalMs: 900,
      targetSize: 56,
      targetSpeed: 0.09,
    }),
    config(3, "aim-decoy", "过关要求：只打高亮目标，不碰 1 个干扰靶。", {
      aimMode: "decoy",
      arrowCount: 8,
      targetCount: 8,
      route: "diagonal",
      failOnFlyOut: false,
      decoyCount: 1,
      targetSize: 56,
      targetSpeed: 0.0018,
    }),
    config(4, "aim-track", "过关要求：8 箭全中椭圆变速轨迹靶。", {
      aimMode: "track",
      arrowCount: 8,
      targetCount: 8,
      route: "ellipse",
      failOnFlyOut: false,
      decoyCount: 0,
      targetSize: 50,
      targetSpeed: 0.002,
    }),
    config(5, "aim-incoming", "过关要求：连续命中所有飞入靶，靶子飞出算失败。", {
      aimMode: "incoming",
      arrowCount: 8,
      targetCount: 8,
      route: "incoming",
      failOnFlyOut: true,
      spawnIntervalMs: 760,
      targetSize: 48,
      targetSpeed: 0.12,
    }),
    config(6, "aim-decoy", "过关要求：只打高亮目标，不碰 2 个干扰靶。", {
      aimMode: "decoy",
      arrowCount: 8,
      targetCount: 8,
      route: "diagonal",
      failOnFlyOut: false,
      decoyCount: 2,
      targetSize: 48,
      targetSpeed: 0.0022,
    }),
    config(7, "aim-track", "过关要求：8 箭全中 8 字轨迹靶。", {
      aimMode: "track",
      arrowCount: 8,
      targetCount: 8,
      route: "figure-eight",
      failOnFlyOut: false,
      decoyCount: 0,
      targetSize: 44,
      targetSpeed: 0.0025,
    }),
    config(8, "aim-incoming", "过关要求：连续命中所有飞入靶，靶子飞出算失败。", {
      aimMode: "incoming",
      arrowCount: 8,
      targetCount: 8,
      route: "incoming",
      failOnFlyOut: true,
      spawnIntervalMs: 620,
      targetSize: 42,
      targetSpeed: 0.15,
    }),
    config(9, "aim-decoy", "过关要求：只打高亮目标，不碰 3 个干扰靶。", {
      aimMode: "decoy",
      arrowCount: 8,
      targetCount: 8,
      route: "diagonal",
      failOnFlyOut: false,
      decoyCount: 3,
      targetSize: 42,
      targetSpeed: 0.0026,
    }),
    config(10, "aim-boss", "过关要求：组合靶场全中，不能射中干扰靶，目标飞出算失败。", {
      aimMode: "boss",
      arrowCount: 10,
      targetCount: 10,
      route: "mixed",
      failOnFlyOut: true,
      decoyCount: 3,
      spawnIntervalMs: 680,
      targetSize: 42,
      targetSpeed: 0.15,
    }),
  ];
}
