import { config } from "./shared.ts";

export function brakingConfigs() {
  return [
    config(1, "braking-single-red", "过关要求：长按前进，红色危险出现时松手，到终点。", {
      hazardCount: 3,
      eventCountMin: 3,
      eventCountMax: 4,
      allowGray: false,
      lanes: 1,
      exitRequired: true,
      speedPerSecond: 14,
      reactionWindowMs: 650,
      eventDurationMs: 550,
      minEventDelayMs: 1400,
      maxEventDelayMs: 2100,
      finishSafeDistance: 12,
    }),
    config(2, "braking-red-gray", "过关要求：红色松手，灰色继续按住，到终点。", {
      hazardCount: 5,
      eventCountMin: 5,
      eventCountMax: 6,
      allowGray: true,
      lanes: 1,
      exitRequired: true,
      speedPerSecond: 12.5,
      reactionWindowMs: 580,
      grayHoldMs: 550,
      eventDurationMs: 550,
      minEventDelayMs: 1200,
      maxEventDelayMs: 1900,
      finishSafeDistance: 12,
    }),
    config(3, "braking-dual-red-rule", "过关要求：请遵守游戏内特殊规则。", {
      hazardCount: 4,
      eventCountMin: 4,
      eventCountMax: 5,
      allowGray: false,
      lanes: 2,
      exitRequired: true,
      speedPerSecond: 11,
      reactionWindowMs: 600,
      eventDurationMs: 600,
      minEventDelayMs: 1200,
      maxEventDelayMs: 1800,
      finishSafeDistance: 12,
      dualRule: "single-red-stop",
    }),
    config(4, "braking-single-red", "过关要求：长按前进，连续处理红色危险，到终点。", {
      hazardCount: 5,
      eventCountMin: 5,
      eventCountMax: 6,
      allowGray: false,
      lanes: 1,
      exitRequired: true,
      speedPerSecond: 11.5,
      reactionWindowMs: 500,
      eventDurationMs: 600,
      minEventDelayMs: 1000,
      maxEventDelayMs: 1700,
      finishSafeDistance: 12,
    }),
    config(5, "braking-red-gray", "过关要求：红色松手，灰色继续按住，随机混合到终点。", {
      hazardCount: 7,
      eventCountMin: 7,
      eventCountMax: 8,
      allowGray: true,
      lanes: 1,
      exitRequired: true,
      speedPerSecond: 10.5,
      reactionWindowMs: 480,
      grayHoldMs: 500,
      eventDurationMs: 600,
      minEventDelayMs: 900,
      maxEventDelayMs: 1500,
      finishSafeDistance: 12,
    }),
    config(6, "braking-dual-red-rule", "过关要求：请遵守游戏内特殊规则。", {
      hazardCount: 6,
      eventCountMin: 6,
      eventCountMax: 7,
      allowGray: false,
      lanes: 2,
      exitRequired: true,
      speedPerSecond: 9.5,
      reactionWindowMs: 520,
      eventDurationMs: 600,
      minEventDelayMs: 900,
      maxEventDelayMs: 1500,
      finishSafeDistance: 12,
      dualRule: "double-red-stop",
    }),
    config(7, "braking-single-red", "过关要求：长按前进，高压处理红色危险，到终点。", {
      hazardCount: 7,
      eventCountMin: 7,
      eventCountMax: 8,
      allowGray: false,
      lanes: 1,
      exitRequired: true,
      speedPerSecond: 9,
      reactionWindowMs: 420,
      eventDurationMs: 650,
      minEventDelayMs: 750,
      maxEventDelayMs: 1350,
      finishSafeDistance: 12,
    }),
    config(8, "braking-red-gray", "过关要求：红色松手，灰色继续按住，高压混合到终点。", {
      hazardCount: 9,
      eventCountMin: 9,
      eventCountMax: 10,
      allowGray: true,
      lanes: 1,
      exitRequired: true,
      speedPerSecond: 8.8,
      reactionWindowMs: 400,
      grayHoldMs: 450,
      eventDurationMs: 650,
      minEventDelayMs: 650,
      maxEventDelayMs: 1250,
      finishSafeDistance: 12,
    }),
    config(9, "braking-dual-red-rule", "过关要求：请遵守游戏内特殊规则。", {
      hazardCount: 8,
      eventCountMin: 8,
      eventCountMax: 9,
      allowGray: false,
      lanes: 2,
      exitRequired: true,
      speedPerSecond: 8.3,
      reactionWindowMs: 450,
      eventDurationMs: 650,
      minEventDelayMs: 650,
      maxEventDelayMs: 1250,
      finishSafeDistance: 12,
      dualRule: "fake-all",
    }),
    config(10, "braking-final-red-gray", "过关要求：请遵守游戏内特殊规则。", {
      hazardCount: 10,
      eventCountMin: 10,
      eventCountMax: 12,
      allowGray: true,
      lanes: 2,
      exitRequired: true,
      speedPerSecond: 7.5,
      reactionWindowMs: 420,
      grayHoldMs: 500,
      eventDurationMs: 650,
      minEventDelayMs: 550,
      maxEventDelayMs: 1100,
      finishSafeDistance: 12,
    }),
  ];
}
