import {
  type MiniGameDefinition,
  type MiniGameDifficulty,
  type MiniGameId,
  type MiniGameLevelConfig,
  type MiniGameLevelKind,
  type MiniGameParams,
} from "./shared.ts";

function level(
  gameId: MiniGameId,
  order: number,
  code: string,
  title: string,
  difficulty: MiniGameDifficulty,
  variant: string,
  description: string,
  goalText: string,
  params: MiniGameParams,
): MiniGameLevelConfig {
  return {
    gameId,
    levelId: `${gameId}-${order}`,
    order,
    kind: "advanced",
    code,
    title,
    difficulty,
    variant,
    description,
    goalText,
    params,
  };
}

function baseLevel(
  gameId: MiniGameId,
  code: string,
  title: string,
  description: string,
  goalText: string,
  params: MiniGameParams,
): MiniGameLevelConfig {
  return {
    gameId,
    levelId: `${gameId}-base`,
    order: 11,
    kind: "base",
    code,
    title,
    difficulty: "基础",
    variant: "基础关",
    description,
    goalText,
    params,
  };
}

function configuredLevel(
  gameId: MiniGameId,
  levelId: string,
  order: number,
  code: string,
  title: string,
  kind: MiniGameLevelKind,
  difficulty: MiniGameDifficulty,
  variant: string,
  description: string,
  goalText: string,
  params: MiniGameParams,
): MiniGameLevelConfig {
  return {
    gameId,
    levelId,
    order,
    kind,
    code,
    title,
    difficulty,
    variant,
    description,
    goalText,
    params,
  };
}

const doodleBaseParams = {
  targetHeightScreens: 3,
  movingPlatformRatio: 0,
  movingPlatformSpeed: 0,
  hazardDensity: 0,
  movingObstacleCount: 0,
  movingHazardSpeed: 0,
  movementPattern: "",
  platformGap: 102,
  requiredRiskPlatforms: 0,
  riskJumpMultiplier: 1,
  dangerLineEnabled: false,
  dangerLineDelay: null,
  dangerLineSpeed: 0,
  riskPlatformWidth: 86,
};

const flappyBaseParams = {
  gateCount: 6,
  movingGateRatio: 0,
  collectibleCount: 0,
  reversedGravity: false,
  reverseDirection: false,
  gapSize: 190,
  speed: 118,
};

const knifeBaseParams = {
  shotCount: 6,
  shotCountdown: null,
  sineRotationEnabled: false,
  phaseDuration: null,
  sweepPerPhase: null,
  forbiddenZoneCount: 0,
  forbiddenZoneRatio: 0,
  initialObstacleCount: 4,
  initialObstacleAngles: "0|90|180|270",
  baseRotationSpeed: 88,
};

const doodleLevels: MiniGameLevelConfig[] = [
  level("doodle", 1, "1-1", "移动平台", "简单", "移动平台", "移动平台比例约 40%，少量危险障碍，速度慢。", "到达 4 屏高度", {
    ...doodleBaseParams,
    targetHeightScreens: 4,
    movingPlatformRatio: 0.4,
    movingPlatformSpeed: 22,
    hazardDensity: 0.45,
    platformGap: 100,
  }),
  level("doodle", 2, "1-2", "移动平台", "普通", "移动平台", "移动平台比例约 70%，中等危险障碍，速度中等。", "到达 6 屏高度", {
    ...doodleBaseParams,
    targetHeightScreens: 6,
    movingPlatformRatio: 0.7,
    movingPlatformSpeed: 34,
    hazardDensity: 0.8,
    platformGap: 104,
  }),
  level("doodle", 3, "1-3", "移动平台", "困难", "移动平台", "全部平台移动，危险障碍更多，速度较快。", "到达 8 屏高度", {
    ...doodleBaseParams,
    targetHeightScreens: 8,
    movingPlatformRatio: 1,
    movingPlatformSpeed: 46,
    hazardDensity: 1.2,
    platformGap: 108,
  }),
  level("doodle", 4, "1-4", "必踩高风险平台", "简单", "必踩高风险平台", "必须踩中 3 个略窄高风险平台，统一 1.6 倍弹跳。", "到达 5 屏高度，必踩 3/3", {
    ...doodleBaseParams,
    targetHeightScreens: 5,
    hazardDensity: 0.45,
    requiredRiskPlatforms: 3,
    riskJumpMultiplier: 1.6,
    riskPlatformWidth: 88,
    platformGap: 100,
  }),
  level("doodle", 5, "1-5", "必踩高风险平台", "普通", "必踩高风险平台", "必须踩中 5 个中等宽度高风险平台，部分位置更偏且会移动。", "到达 7 屏高度，必踩 5/5", {
    ...doodleBaseParams,
    targetHeightScreens: 7,
    hazardDensity: 0.8,
    movingPlatformRatio: 0,
    movingPlatformSpeed: 0,
    requiredRiskPlatforms: 5,
    riskJumpMultiplier: 1.6,
    riskPlatformWidth: 76,
    platformGap: 104,
  }),
  level("doodle", 6, "1-6", "必踩高风险平台", "困难", "必踩高风险平台", "必须踩中 7 个更窄高风险平台，更多平台移动并带移动障碍压力。", "到达 9 屏高度，必踩 7/7", {
    ...doodleBaseParams,
    targetHeightScreens: 9,
    movingPlatformRatio: 0,
    movingPlatformSpeed: 0,
    hazardDensity: 1.15,
    movingObstacleCount: 0,
    movingHazardSpeed: 0,
    movementPattern: "",
    requiredRiskPlatforms: 7,
    riskJumpMultiplier: 1.6,
    riskPlatformWidth: 64,
    platformGap: 108,
  }),
  level("doodle", 7, "1-7", "移动障碍", "简单", "移动障碍", "少量移动障碍在平台旁缓慢移动，主要练习躲避节奏。", "到达 5 屏高度", {
    ...doodleBaseParams,
    targetHeightScreens: 5,
    hazardDensity: 0.45,
    movingObstacleCount: 5,
    movingHazardSpeed: 24,
    movementPattern: "horizontal",
    platformGap: 100,
  }),
  level("doodle", 8, "1-8", "移动障碍", "普通", "移动障碍", "移动障碍数量增加，部分会穿过常用跳跃路线。", "到达 7 屏高度", {
    ...doodleBaseParams,
    targetHeightScreens: 7,
    hazardDensity: 0.85,
    movingObstacleCount: 9,
    movingHazardSpeed: 34,
    movementPattern: "horizontal|vertical|patrolDiagonal",
    platformGap: 104,
  }),
  level("doodle", 9, "1-9", "移动障碍", "困难", "移动障碍", "较多移动障碍持续压迫连续平台之间的上升路线。", "到达 9 屏高度", {
    ...doodleBaseParams,
    targetHeightScreens: 9,
    hazardDensity: 1.2,
    movingObstacleCount: 13,
    movingHazardSpeed: 44,
    movementPattern: "horizontal|vertical|patrolDiagonal|orbitSmall|pulse|slowCross",
    platformGap: 108,
  }),
  level("doodle", 10, "1-10", "最终关", "最终", "综合最终关", "全移动平台，8 个必踩高风险平台，后段加入更多移动障碍。", "到达 10 屏高度，必踩 8/8", {
    ...doodleBaseParams,
    targetHeightScreens: 10,
    movingPlatformRatio: 1,
    movingPlatformSpeed: 42,
    hazardDensity: 1.3,
    movingObstacleCount: 20,
    movingHazardSpeed: 46,
    movementPattern: "horizontal|vertical|patrolDiagonal|orbitSmall|pulse|slowCross",
    finalObstacleStartScreen: 1,
    requiredRiskPlatforms: 8,
    riskJumpMultiplier: 1.6,
    dangerLineEnabled: false,
    riskPlatformWidth: 68,
    platformGap: 108,
  }),
  baseLevel("doodle", "基础关", "Doodle Jump 基础关", "少量静态平台，无移动障碍，无必踩高风险平台。", "到达 3 屏高度", doodleBaseParams),
];

const flappyLevels: MiniGameLevelConfig[] = [
  level("flappy", 1, "2-1", "移动门", "简单", "移动门", "8 门，30% 移动门，缝隙大，速度慢。", "通过 8 个门", {
    ...flappyBaseParams,
    gateCount: 8,
    movingGateRatio: 0.3,
    gapSize: 190,
    speed: 116,
    movingGateSpeed: 1,
  }),
  level("flappy", 2, "2-2", "移动门", "普通", "移动门", "10 门，50% 移动门，缝隙中等。", "通过 10 个门", {
    ...flappyBaseParams,
    gateCount: 10,
    movingGateRatio: 0.5,
    gapSize: 168,
    speed: 128,
    movingGateSpeed: 1.35,
  }),
  level("flappy", 3, "2-3", "移动门", "困难", "移动门", "12 门，70% 移动门，缝隙略小。", "通过 12 个门", {
    ...flappyBaseParams,
    gateCount: 12,
    movingGateRatio: 0.7,
    gapSize: 152,
    speed: 140,
    movingGateSpeed: 1.7,
  }),
  level("flappy", 4, "2-4", "收集路径道具", "简单", "收集路径道具", "8 门，必须收集 4 个接近安全中心线的道具。", "通过 8 门，收集 4/4", {
    ...flappyBaseParams,
    gateCount: 8,
    collectibleCount: 4,
    gapSize: 190,
    speed: 116,
    collectibleOffset: 0.18,
  }),
  level("flappy", 5, "2-5", "收集路径道具", "普通", "收集路径道具", "10 门，必须收集 6 个略微偏上或偏下的道具。", "通过 10 门，收集 6/6", {
    ...flappyBaseParams,
    gateCount: 10,
    collectibleCount: 6,
    gapSize: 168,
    speed: 128,
    collectibleOffset: 0.28,
  }),
  level("flappy", 6, "2-6", "收集路径道具", "困难", "收集路径道具", "12 门，必须收集 8 个更靠近缝隙边缘的道具。", "通过 12 门，收集 8/8", {
    ...flappyBaseParams,
    gateCount: 12,
    collectibleCount: 8,
    gapSize: 152,
    speed: 138,
    collectibleOffset: 0.36,
  }),
  level("flappy", 7, "2-7", "重力反转 + 反向移动", "简单", "反重力反向", "6 门，角色从右往左移动，不点击向上漂，点击向下压。", "通过 6 个门", {
    ...flappyBaseParams,
    gateCount: 6,
    reversedGravity: true,
    reverseDirection: true,
    gapSize: 196,
    speed: 106,
  }),
  level("flappy", 8, "2-8", "重力反转 + 反向移动", "普通", "反重力反向", "8 门，反向移动速度中等，缝隙中等。", "通过 8 个门", {
    ...flappyBaseParams,
    gateCount: 8,
    reversedGravity: true,
    reverseDirection: true,
    gapSize: 172,
    speed: 122,
  }),
  level("flappy", 9, "2-9", "重力反转 + 反向移动", "困难", "反重力反向", "10 门，少量移动门，反向速度较快。", "通过 10 个门", {
    ...flappyBaseParams,
    gateCount: 10,
    movingGateRatio: 0,
    reversedGravity: true,
    reverseDirection: true,
    gapSize: 154,
    speed: 136,
    movingGateSpeed: 1.2,
  }),
  level("flappy", 10, "2-10", "最终关", "最终", "综合最终关", "反向移动和反重力，13 门，移动门与必收集道具同时出现。", "通过 13 门，收集 7/7", {
    ...flappyBaseParams,
    gateCount: 13,
    movingGateRatio: 0.45,
    collectibleCount: 7,
    reversedGravity: true,
    reverseDirection: true,
    gapSize: 162,
    speed: 132,
    movingGateSpeed: 1.35,
    collectibleOffset: 0.3,
  }),
  baseLevel("flappy", "基础关", "Flappy Bird 基础关", "普通固定门，通过 6 个门即可。", "通过 6 个门", flappyBaseParams),
];

const knifeLevels: MiniGameLevelConfig[] = [
  level("knife", 1, "3-1", "发射倒计时", "简单", "发射倒计时", "7 发，每发 2.5 秒倒计时，初始障碍 4 个。", "命中 7 发", {
    ...knifeBaseParams,
    shotCount: 7,
    shotCountdown: 2.5,
    initialObstacleCount: 4,
    baseRotationSpeed: 82,
  }),
  level("knife", 2, "3-2", "发射倒计时", "普通", "发射倒计时", "9 发，每发 2.5 秒倒计时，初始障碍 4 个。", "命中 9 发", {
    ...knifeBaseParams,
    shotCount: 9,
    shotCountdown: 2.5,
    initialObstacleCount: 4,
    baseRotationSpeed: 96,
  }),
  level("knife", 3, "3-3", "发射倒计时", "困难", "发射倒计时", "11 发，每发 2.0 秒倒计时，初始障碍 4 个。", "命中 11 发", {
    ...knifeBaseParams,
    shotCount: 11,
    shotCountdown: 2,
    initialObstacleCount: 4,
    baseRotationSpeed: 106,
  }),
  level("knife", 4, "3-4", "转速正弦波动", "简单", "转速正弦波动", "7 发，每发 2.0 秒倒计时，正弦周期 3.0 秒，初始障碍 4 个。", "命中 7 发", {
    ...knifeBaseParams,
    shotCount: 7,
    shotCountdown: 2,
    sineRotationEnabled: true,
    phaseDuration: 3,
    sweepPerPhase: 390,
    initialObstacleCount: 4,
    baseRotationSpeed: 138,
  }),
  level("knife", 5, "3-5", "转速正弦波动", "普通", "转速正弦波动", "9 发，正弦周期 2.8 秒，初始障碍 4 个。", "命中 9 发", {
    ...knifeBaseParams,
    shotCount: 9,
    sineRotationEnabled: true,
    phaseDuration: 2.8,
    sweepPerPhase: 405,
    initialObstacleCount: 4,
    baseRotationSpeed: 154,
  }),
  level("knife", 6, "3-6", "转速正弦波动", "困难", "转速正弦波动", "11 发，正弦周期 2.55 秒，初始障碍 4 个。", "命中 11 发", {
    ...knifeBaseParams,
    shotCount: 11,
    sineRotationEnabled: true,
    phaseDuration: 2.55,
    sweepPerPhase: 420,
    initialObstacleCount: 4,
    baseRotationSpeed: 166,
  }),
  level("knife", 7, "3-7", "不可插区域", "简单", "不可插区域", "7 发，每发 1.5 秒倒计时，初始障碍 4 个，1 块不可插区域，总面积约 12%。", "命中 7 发，避开禁区", {
    ...knifeBaseParams,
    shotCount: 7,
    shotCountdown: 1.5,
    forbiddenZoneCount: 1,
    forbiddenZoneRatio: 0.12,
    initialObstacleCount: 4,
    baseRotationSpeed: 90,
  }),
  level("knife", 8, "3-8", "不可插区域", "普通", "不可插区域", "9 发，初始障碍 4 个，2 块不可插区域，总面积约 18%。", "命中 9 发，避开禁区", {
    ...knifeBaseParams,
    shotCount: 9,
    forbiddenZoneCount: 2,
    forbiddenZoneRatio: 0.18,
    initialObstacleCount: 4,
    baseRotationSpeed: 98,
  }),
  level("knife", 9, "3-9", "不可插区域", "困难", "不可插区域", "11 发，3 块不可插区域，总面积约 24%。", "命中 11 发，避开禁区", {
    ...knifeBaseParams,
    shotCount: 11,
    forbiddenZoneCount: 3,
    forbiddenZoneRatio: 0.24,
    initialObstacleCount: 3,
    initialObstacleAngles: null,
    baseRotationSpeed: 106,
  }),
  level("knife", 10, "3-10", "最终关", "最终", "综合最终关", "13 发，每发 2.5 秒倒计时，正弦转速和不可插区域同时出现。", "命中 13 发，避开禁区和旧刀", {
    ...knifeBaseParams,
    shotCount: 13,
    shotCountdown: 2.5,
    sineRotationEnabled: true,
    phaseDuration: 2.7,
    sweepPerPhase: 405,
    forbiddenZoneCount: 2,
    forbiddenZoneRatio: 0.2,
    initialObstacleCount: 3,
    initialObstacleAngles: null,
    baseRotationSpeed: 152,
  }),
  baseLevel("knife", "基础关", "Knife Hit 基础关", "普通匀速转盘，发射 6 个，初始障碍 4 个。", "命中 6 发", knifeBaseParams),
];

const squareJumpBaseParams = {
  implementation: "square-jump",
  jumpsRequired: 8,
  platformWidth: 110,
  basePlatformWidthMin: 92,
  basePlatformWidthMax: 124,
  distanceMin: 136,
  distanceMax: 226,
  minJumpDistance: 28,
  maxJumpDistance: 220,
  precomputedJumpAnimation: true,
  powerDistanceMin: 34,
  powerDistanceMax: 220,
  secondPowerDistanceMin: 30,
  secondPowerDistanceMax: 180,
  targetLandingPadding: 9,
  flyAwayLandingCatchDepth: 40,
  keepNextPlatformVisible: true,
  landingKeepsActualX: true,
  useCameraScale: true,
  sweptLandingCollision: false,
  doubleJumpEnabled: false,
  cyclingChargeOnDoubleJump: false,
  currentAnchorRatio: 0.28,
  nextMinRatio: 0.62,
  nextMaxRatio: 0.84,
  movingPlatformCount: 0,
  movingSpeed: 0,
  movingRange: 0,
  timedWindow: null,
  timedFinalWindow: null,
  gravityPattern: "normal",
  gravityChallenge: false,
  finalMix: false,
};

const squareJumpVariantParams = {
  ...squareJumpBaseParams,
  precomputedJumpAnimation: true,
  sweptLandingCollision: false,
};

const squareJumpLevels: MiniGameLevelConfig[] = [
  configuredLevel("square-jump", "square-jump-base", 0, "基础关", "基础关", "base", "基础", "基础关", "长按蓄力，松手让小方块跳到下一个平台，连续成功 5 次通关。", "连续跳到 5 个平台", squareJumpBaseParams),
  configuredLevel("square-jump", "square-jump-moving-easy", 1, "1-1", "移动落点", "advanced", "简单", "移动落点", "1 个慢速移动平台，平台较宽，距离变化小。", "预判移动平台并完成 4 次跳跃", {
    ...squareJumpVariantParams,
    jumpsRequired: 7,
    platformWidth: 100,
    distanceMin: 142,
    distanceMax: 218,
    movingPlatformCount: 1,
    movingSpeed: 1.35,
    movingRange: 34,
  }),
  configuredLevel("square-jump", "square-jump-moving-normal", 2, "1-2", "移动落点", "advanced", "普通", "移动落点", "连续 3 个中速移动平台，宽度正常，距离略随机。", "预判移动平台并完成 5 次跳跃", {
    ...squareJumpVariantParams,
    jumpsRequired: 8,
    platformWidth: 82,
    distanceMin: 156,
    distanceMax: 218,
    movingPlatformCount: 3,
    movingSpeed: 1.9,
    movingRange: 48,
  }),
  configuredLevel("square-jump", "square-jump-moving-hard", 3, "1-3", "移动落点", "advanced", "困难", "移动落点", "多个快速窄平台会反向移动，需要提前预判落点。", "预判快速移动平台并完成 6 次跳跃", {
    ...squareJumpVariantParams,
    jumpsRequired: 9,
    platformWidth: 68,
    distanceMin: 164,
    distanceMax: 204,
    movingPlatformCount: 9,
    movingStaticEvery: 4,
    movingSpeed: 2.6,
    movingRange: 58,
    reverseMoving: true,
  }),
  configuredLevel("square-jump", "square-jump-double-easy", 4, "2-1", "二段跳跃", "advanced", "简单", "二段跳跃", "跳起后可在空中再次蓄力，悬停后释放完成二段跳。", "用二段跳完成 4 次跳跃", {
    ...squareJumpVariantParams,
    jumpsRequired: 5,
    platformWidth: 96,
    distanceMin: 296,
    distanceMax: 350,
    powerDistanceMax: 220,
    secondPowerDistanceMax: 180,
    doubleJumpEnabled: true,
    cyclingChargeOnDoubleJump: true,
    timedWindow: null,
    timedFinalWindow: null,
  }),
  configuredLevel("square-jump", "square-jump-double-normal", 5, "2-2", "二段跳跃", "advanced", "普通", "二段跳跃", "平台距离更远，空中二段蓄力会悬停，释放后继续前进。", "用二段跳完成 5 次跳跃", {
    ...squareJumpVariantParams,
    jumpsRequired: 6,
    platformWidth: 82,
    distanceMin: 320,
    distanceMax: 385,
    powerDistanceMax: 220,
    secondPowerDistanceMax: 180,
    doubleJumpEnabled: true,
    cyclingChargeOnDoubleJump: true,
    timedWindow: null,
    timedFinalWindow: null,
  }),
  configuredLevel("square-jump", "square-jump-double-hard", 6, "2-3", "二段跳跃", "advanced", "困难", "二段跳跃", "窄平台和远距离同时出现，需要在空中把握二段蓄力时机。", "用二段跳完成 6 次跳跃", {
    ...squareJumpVariantParams,
    jumpsRequired: 7,
    platformWidth: 70,
    distanceMin: 350,
    distanceMax: 415,
    powerDistanceMax: 220,
    secondPowerDistanceMax: 180,
    doubleJumpEnabled: true,
    cyclingChargeOnDoubleJump: true,
    timedWindow: null,
    timedFinalWindow: null,
  }),
  configuredLevel("square-jump", "square-jump-gravity-easy", 7, "3-1", "重力平台", "advanced", "简单", "重力平台", "只出现正常和变轻平台，变轻后会跳得更远。", "根据重力状态完成 4 次跳跃", {
    ...squareJumpVariantParams,
    jumpsRequired: 7,
    platformWidth: 96,
    distanceMin: 132,
    distanceMax: 220,
    gravityPattern: "normal|light|normal|light",
    gravityChallenge: true,
  }),
  configuredLevel("square-jump", "square-jump-gravity-normal", 8, "3-2", "重力平台", "advanced", "普通", "重力平台", "正常、变轻、加重平台都会出现，需要连续判断当前状态。", "根据三种重力完成 5 次跳跃", {
    ...squareJumpVariantParams,
    jumpsRequired: 8,
    platformWidth: 82,
    distanceMin: 138,
    distanceMax: 220,
    gravityPattern: "normal|light|heavy|normal|light",
    gravityChallenge: true,
  }),
  configuredLevel("square-jump", "square-jump-gravity-hard", 9, "3-3", "重力平台", "advanced", "困难", "重力平台", "反向考验更多：变轻接近平台、加重接远平台，容错更低。", "根据重力反向考验完成 6 次跳跃", {
    ...squareJumpVariantParams,
    jumpsRequired: 12,
    platformWidth: 68,
    distanceMin: 142,
    distanceMax: 214,
    gravityPattern: "light|normal|heavy|light|heavy|normal",
    gravityChallenge: true,
  }),
  configuredLevel("square-jump", "square-jump-final", 10, "最终关", "方块终跃", "advanced", "最终", "综合最终关", "综合移动落点、二段跳和重力切换平台，一路跳到终点。", "连续跳到终点平台", {
    ...squareJumpVariantParams,
    jumpsRequired: 15,
    platformWidth: 70,
    distanceMin: 330,
    distanceMax: 410,
    movingPlatformCount: 3,
    movingSpeed: 2.1,
    movingRange: 54,
    powerDistanceMax: 220,
    secondPowerDistanceMax: 180,
    doubleJumpEnabled: true,
    cyclingChargeOnDoubleJump: true,
    timedWindow: null,
    timedFinalWindow: null,
    gravityPattern: "normal|normal|light|normal|heavy|light|normal|normal",
    gravityChallenge: true,
    finalMix: true,
    reverseMoving: true,
  }),
].map((level) => ({
  ...level,
  description:
    level.levelId === "square-jump-base"
      ? `长按蓄力，松手让小方块跳到下一个平台，连续成功 ${level.params.jumpsRequired} 次通关。`
      : level.description,
  goalText:
    level.levelId === "square-jump-final"
      ? `连续完成 ${level.params.jumpsRequired} 次跳跃到终点平台`
      : `连续完成 ${level.params.jumpsRequired} 次跳跃`,
}));

const fallDownBaseParams = {
  implementation: "fall-down",
  layersRequired: 10,
  platformWidth: 112,
  platformGapMin: 96,
  platformGapMax: 132,
  playerSpeed: 288,
  topPressureSpeed: 42,
  movingPlatformCount: 0,
  movingSpeed: 0,
  movingRange: 0,
  fragilePlatformCount: 0,
  fragileTime: 0,
  dangerPlatformCount: 0,
  fallingHazardCount: 0,
  fallingHazardSpeed: 132,
  fallingHazardSize: 22,
  ledgePlatformCount: 0,
  finalMix: false,
};

const fallDownLevels: MiniGameLevelConfig[] = [
  configuredLevel("fall-down", "fall-down-base", 0, "基础关", "一路向下基础关", "base", "基础", "基础关", "左右半屏控制小方块横向移动，落到更低的平台并下降到终点层。", "下降 10 层到终点", fallDownBaseParams),
  configuredLevel("fall-down", "fall-down-moving-easy", 1, "1-1", "移动层板", "advanced", "简单", "移动层板", "少量移动平台，宽度较大，练习预判下落位置。", "通过慢速移动层板", {
    ...fallDownBaseParams,
    layersRequired: 14,
    platformWidth: 104,
    platformGapMin: 98,
    platformGapMax: 136,
    movingPlatformCount: 7,
    movingSpeed: 0.75,
    movingRange: 52,
    topPressureSpeed: 44,
  }),
  configuredLevel("fall-down", "fall-down-moving-normal", 2, "1-2", "移动层板", "advanced", "普通", "移动层板", "移动平台数量增加，间距变大，需要提前调整左右位置。", "通过连续移动层板", {
    ...fallDownBaseParams,
    layersRequired: 18,
    platformWidth: 84,
    platformGapMin: 112,
    platformGapMax: 154,
    topPressureSpeed: 54,
    movingPlatformCount: 11,
    movingSpeed: 1,
    movingRange: 68,
    fallingHazardCount: 2,
    fallingHazardSpeed: 132,
    fallingHazardSize: 22,
  }),
  configuredLevel("fall-down", "fall-down-moving-hard", 3, "1-3", "移动层板", "advanced", "困难", "移动层板", "连续移动窄平台，部分方向相反，顶部压线更快。", "通过高压移动层板", {
    ...fallDownBaseParams,
    layersRequired: 22,
    platformWidth: 68,
    platformGapMin: 124,
    platformGapMax: 172,
    topPressureSpeed: 66,
    movingPlatformCount: 16,
    movingSpeed: 1.35,
    movingRange: 88,
    fallingHazardCount: 2,
    fallingHazardSpeed: 158,
    fallingHazardSize: 23,
    ledgePlatformCount: 5,
    reverseMoving: true,
  }),
  configuredLevel("fall-down", "fall-down-fragile-easy", 4, "2-1", "脆弱层板", "advanced", "简单", "脆弱层板", "少量脆弱平台，踩上后约 1.8 秒碎裂。", "避开碎裂压力下降", {
    ...fallDownBaseParams,
    layersRequired: 14,
    platformWidth: 104,
    topPressureSpeed: 44,
    fragilePlatformCount: 7,
    fragileTime: 1.8,
  }),
  configuredLevel("fall-down", "fall-down-fragile-normal", 5, "2-2", "脆弱层板", "advanced", "普通", "脆弱层板", "脆弱平台数量增加，碎裂时间更短，不能停留太久。", "连续通过脆弱层板", {
    ...fallDownBaseParams,
    layersRequired: 18,
    platformWidth: 84,
    platformGapMin: 110,
    platformGapMax: 152,
    topPressureSpeed: 54,
    fragilePlatformCount: 11,
    fragileTime: 1.35,
    fallingHazardCount: 2,
    fallingHazardSpeed: 132,
    fallingHazardSize: 22,
  }),
  configuredLevel("fall-down", "fall-down-fragile-hard", 6, "2-3", "脆弱层板", "advanced", "困难", "脆弱层板", "连续脆弱窄平台，最后几层几乎不能停留。", "在碎裂前连续下降", {
    ...fallDownBaseParams,
    layersRequired: 22,
    platformWidth: 66,
    platformGapMin: 124,
    platformGapMax: 172,
    topPressureSpeed: 68,
    fragilePlatformCount: 16,
    fragileTime: 0.95,
    fallingHazardCount: 2,
    fallingHazardSpeed: 160,
    fallingHazardSize: 23,
    ledgePlatformCount: 5,
  }),
  configuredLevel("fall-down", "fall-down-danger-easy", 7, "3-1", "危险层板", "advanced", "简单", "危险层板", "少量红色危险平台，安全路线明显。", "避开危险平台下降", {
    ...fallDownBaseParams,
    layersRequired: 14,
    platformWidth: 104,
    topPressureSpeed: 46,
    dangerPlatformCount: 5,
  }),
  configuredLevel("fall-down", "fall-down-danger-normal", 8, "3-2", "危险层板", "advanced", "普通", "危险层板", "危险平台数量增加，部分安全平台更窄。", "选择安全层板下降", {
    ...fallDownBaseParams,
    layersRequired: 18,
    platformWidth: 82,
    platformGapMin: 112,
    platformGapMax: 156,
    topPressureSpeed: 58,
    dangerPlatformCount: 8,
    fallingHazardCount: 2,
    fallingHazardSpeed: 146,
    fallingHazardSize: 22,
  }),
  configuredLevel("fall-down", "fall-down-danger-hard", 9, "3-3", "危险层板", "advanced", "困难", "危险层板", "危险平台和窄安全平台交错，需要连续选择路线。", "连续避开危险层板", {
    ...fallDownBaseParams,
    layersRequired: 22,
    platformWidth: 66,
    platformGapMin: 124,
    platformGapMax: 174,
    topPressureSpeed: 72,
    dangerPlatformCount: 11,
    fallingHazardCount: 2,
    fallingHazardSpeed: 180,
    fallingHazardSize: 24,
    ledgePlatformCount: 5,
  }),
  configuredLevel("fall-down", "fall-down-final", 10, "最终关", "百层试炼", "advanced", "最终", "综合最终关", "综合移动、脆弱和危险层板，下降到终点平台。", "完成百层试炼", {
    ...fallDownBaseParams,
    layersRequired: 30,
    platformWidth: 72,
    platformGapMin: 118,
    platformGapMax: 170,
    topPressureSpeed: 74,
    movingPlatformCount: 12,
    movingSpeed: 1.15,
    movingRange: 86,
    fragilePlatformCount: 10,
    fragileTime: 1,
    dangerPlatformCount: 10,
    fallingHazardCount: 4,
    fallingHazardSpeed: 178,
    fallingHazardSize: 24,
    ledgePlatformCount: 8,
    finalMix: true,
    reverseMoving: true,
  }),
];

export const MINI_GAME_DEFINITIONS: MiniGameDefinition[] = [
  {
    id: "doodle",
    title: "Doodle Jump 型",
    shortTitle: "Doodle",
    summary: "左右拖动，踩平台上升",
    instruction: "左右拖动控制角色，踩一次性平台向上，到达目标高度通关。",
    levels: doodleLevels,
  },
  {
    id: "flappy",
    title: "Flappy Bird 型",
    shortTitle: "Flappy",
    summary: "点击控制高度，穿过障碍",
    instruction: "点击屏幕调整高度，穿过门，收集关卡要求的道具。",
    levels: flappyLevels,
  },
  {
    id: "knife",
    title: "Knife Hit 型",
    shortTitle: "Knife",
    summary: "点击发射，命中转盘",
    instruction: "点击发射，避开已插入物体和不可插区域，发射完指定数量通关。",
    levels: knifeLevels,
  },
  {
    id: "square-jump",
    title: "方块跃迁",
    shortTitle: "方块跃迁",
    summary: "长按蓄力，松手跳到平台",
    instruction: "长按屏幕蓄力，松手让小方块向右跳跃。根据移动、限时和重力平台调整节奏。",
    levels: squareJumpLevels,
  },
  {
    id: "fall-down",
    title: "一路向下",
    shortTitle: "一路向下",
    summary: "横向移动，落到下方平台",
    instruction: "左右半屏控制小方块横向移动，持续落到更低的平台，避开危险层板和顶部压线。",
    levels: fallDownLevels,
  },
];

export function getMiniGame(gameId: MiniGameId): MiniGameDefinition {
  const game = MINI_GAME_DEFINITIONS.find((item) => item.id === gameId);
  if (!game) throw new Error(`Unknown mini game: ${gameId}`);
  return game;
}

export function getMiniGameLevels(gameId: MiniGameId): MiniGameLevelConfig[] {
  return getMiniGame(gameId).levels;
}

export function getMiniGameLevel(gameId: MiniGameId, levelId: string): MiniGameLevelConfig {
  const levelConfig = getMiniGameLevels(gameId).find((item) => item.levelId === levelId);
  if (!levelConfig) throw new Error(`Unknown mini game level: ${gameId}/${levelId}`);
  return levelConfig;
}
